# Author: Yuxuan Wu

project_dir: /home/wu/projects/scExtract
init_config_ini: config.ini
output_suffix: claude3

debug: False
applied_files: all

# Step 1: Auto extract
config_pkl: config.pkl
log_file: auto_extract.log

# Step 2: SingleR analysis
ref_data: HumanPrimaryCellAtlas
ref_features: symbol
ref_labels: main
singler_key: singler

# Step 3: Benchmarking
true_key: cell_type
method: embedding
predict_group_key: scextract,no_context_annotation,singler
similarity_key: similarity_scextract,similarity_no_context_annotation,similarity_singler

